### ISSUE TITLE
Want to integrate in my project.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [cgoldsby/LoginCritter#8]
Am I allowed to integrate same demo as yours, into my project?
Will there be any Policy that will broken if I integrate the same in future?

**Comment by cgoldsby** [comment]
Hi @Rashesh-Bosamiya, 

Yes, you can integrate this demo into your project. This project is distributed under the `MIT` license so you are free to copy, modify and use it as you see fit.

This demo is just a side project so I can make no promises to breaking things in the future. I may add or change functionality. So, it is best to fork this project because `master` may change drastically.
